### ISSUE TITLE
Aggregate function support for Linq

### ISSUE THREAD

**Issue by nuitsjp** [Cysharp/UnitGenerator#23]
I am thinking it would be useful to be able to support Linq aggregate functions(Sum, Max, Min, Avg, Aggregate).
If you are willing to incorporate it, I will try to implement it.
What do you think?

I will probably do it little by little when I have time, so I can't do it right away.

**Comment by neuecc** [comment]
We're investigating it now.

**Comment by hadashiA** [comment]
We considered supporting the LINQ extension method, but regrettably decided not to.

NOTE: 
- The scope of LINQ functionality is so broad that it is a bit difficult to draw a line as to how far we will go.
  - We considered implementing a generic math interface to get LINQ support. However, LINQ does not seem to release generic math support as a public api.
    - refs:  https://github.com/dotnet/runtime/issues/64031
- In C#, it could be considered no surprise that even types that can perform `+` and `-` operations cannot `.Sum`.
    - There are ways to aggregate, such as `.Sum(unit => unit.AsPrimitive())`.
    - It probably depends on the frequency of whether or not we need shorthand APIs.
    - You may also define Enumerable extension methods if you wish.
