### ISSUE TITLE
Generate correct ValueConverter for EFCore

### ISSUE THREAD

**Issue by cdrfenix** [Cysharp/UnitGenerator#25]
Hi, great library i like the idea in general, one thing tho is that when using multiple values for a value object and using the _UnitGenerateOptions.EntityFrameworkValueConverter_ option, the generated code wont work.

According to the EF documentation when using complex value objects (with multiple values) it will be mapped to one column (till EF8), hence it should be serialized (recommended to JSON).

https://learn.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations

```
.HasConversion(
        v => JsonSerializer.Serialize(v, (JsonSerializerOptions)null),
        v => JsonSerializer.Deserialize<Money>(v, (JsonSerializerOptions)null));
```

Thanks.

**Comment by hadashiA** [comment]
Hi.  Thanks fro the report.

> when using multiple values for a value object

Perhaps this is not the recommended usage for this library. It is assumed that primitive types are encapsulated as `value`, so if you want to have multiple properties, it is better to define structs as usual.

If I have misunderstood something, please reopen with specific use cases. Thanks.
