### ISSUE TITLE
Skipping Options and setting ToStringFromat breaks code generation

### ISSUE THREAD

**Issue by slimshader** [Cysharp/UnitGenerator#33]
Hi,

when a struct is defined like this:
```
[UnitOf(typeof(string),  ToStringFormat = "null")]
public partial struct ProjectId
```

meaing it skips Options paramater, then no code is generated for the rest of the partial type, fix is to explicitly define options as None:

```
[UnitOf(typeof(string), UnitGenerateOptions.None, ToStringFormat = "null")]
public partial struct ProjectId
```

**Comment by hadashiA** [comment]
Thanks for the report!
Fixed in #34.
