### ISSUE TITLE
Missing IParsable<TSelf> and IFormattable interface implementation

### ISSUE THREAD

**Issue by timotyturini** [Cysharp/UnitGenerator#39]
I found this source generator very powerful and I love it, but there is some missing functionality about globalization:

- [IParsable&lt;TSelf&gt;](https://learn.microsoft.com/en-us/dotnet/api/system.iparsable-1) implementation is missing, and the exposed `Parse`/`TryParse` method do not accept an `IFormatProvider` parameter:
```
// UnitGenerateOptions.ParseMethod

public static SomeInteger Parse(string s)
{
    return new SomeInteger(int.Parse(s));
}

public static bool TryParse(string s, out SomeInteger result)
{
    if (int.TryParse(s, out var r))
    {
        result = new SomeInteger(r);
        return true;
    }
    else
    {
        result = default(SomeInteger);
        return false;
    }
}
```

- [IFormattable](https://learn.microsoft.com/en-us/dotnet/api/system.iformattable) implementation also is missing, with similar drawbacks:
```
public override string ToString() => value.ToString();
```

I guess both implementations requires checking the underlying type to ensure that it supports those interfaces and, in that case, implement and pass-through the aforementioned `IFormatProvider`.

Could be sweet to also expose `ToString(string format)` methods when available on the underlying type, but without a system interface flagging it, i admit is a bit tricky.

Side note: even i'm developing on C# from 10+ years this is my actual first github interaction, and -if you are OK with it- I do wish to contribute about this issue.

**Comment by timotyturini** [comment]
In addition, i discovered that the [IParsable&lt;TSelf&gt;](https://learn.microsoft.com/en-us/dotnet/api/system.iparsable-1) interface exposes an overload generally not available in older frameworks (<=NET6.0):

```
public interface IParsable<TSelf> where TSelf : IParsable<TSelf>?
{
    static abstract TSelf Parse(string s, IFormatProvider? provider);
    static abstract bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, [MaybeNullWhen(false)] out TSelf result);
}
```

Here's the NET6.0 `Parse`/`TryParse `overloads for the type `System.Int32`:

```
public static Int32 Parse(string s, IFormatProvider? provider);
public static Int32 Parse(string s, NumberStyles style, IFormatProvider? provider);
public static Int32 Parse(string s);
public static Int32 Parse(ReadOnlySpan<char> s, NumberStyles style = NumberStyles.Integer, IFormatProvider? provider = null);
public static Int32 Parse(string s, NumberStyles style);
public static bool TryParse([NotNullWhen(true)] string? s, NumberStyles style, IFormatProvider? provider, out Int32 result);
public static bool TryParse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider? provider, out Int32 result);
public static bool TryParse(ReadOnlySpan<char> s, out Int32 result);
public static bool TryParse([NotNullWhen(true)] string? s, out Int32 result);
```

As you can see there is no match, so it should be handled with a preprocessor IF directive

**Comment by neuecc** [comment]
Thank you, that's a great suggestion.  
And I'm sorry, we have implemented it based on your proposal.  
In any case, I appreciate it.
