### ISSUE TITLE
Unity 2021.2 integration

### ISSUE THREAD

**Issue by lupin-de-mid** [Cysharp/UnitGenerator#6]
"C# Source Generator feature is rely on C# 9.0. Currently Unity(2020) does not support C# 9.0 so can not use directly. "
According to  https://docs.unity3d.com/2021.2/Documentation/Manual/CSharpCompiler.html
Unity support C# 90  with small exclusion. So may be it is possible to integrate  UniyGenerator in Unity Editor without additional sln?

**Comment by neuecc** [comment]
No, Unity has indeed added support for C# 9.0, except for SourceGenerator.
Probably a lot of disruptive work needs to be done, such as supporting the new SDK csproj and incorporating the compile phase against Roslyn.

**Comment by neuecc** [comment]
I've reported to forum.
https://forum.unity.com/threads/unity-future-net-development-status.1092205/page-11#post-7715218

**Comment by neuecc** [comment]
Sorry, I misunderstood the behavior.
I've added the documentation to make it work, and it works perfectly.
https://github.com/Cysharp/UnitGenerator#use-for-unity

**Comment by lupin-de-mid** [comment]
For me in unity '2021.2.9f1` it works only if i place `UnitGenerator.dll` in root of `Assets`
