### ISSUE TITLE
Multiple generation of UnitOfAttribute.cs

### ISSUE THREAD

**Issue by pellea** [Cysharp/UnitGenerator#7]
I use UnitOf in a class library L. 
This class library is referenced in another project A. 
Project A contains other source generators (not sure if it is relevant or not).

When building the solution, the `UnitOfAttributes` is added in the class library L **AND** in Project A (while the `UnitGenerator` is only referenced in the class library L).
  
This yields an exception:
```
xxx\UnitGenerator\UnitGenerator.SourceGenerator\UnitOfAttribute.cs(11,20,11,35): error CS0101: The namespace 'UnitGenerator' already contains a definition for 'UnitOfAttribute'
xxx\UnitGenerator\UnitGenerator.SourceGenerator\UnitOfAttribute.cs(26,19,26,38): error CS0101: The namespace 'UnitGenerator' already contains a definition for 'UnitGenerateOptions'
xxx\UnitGenerator\UnitGenerator.SourceGenerator\UnitOfAttribute.cs(10,6,10,20): error CS0579: Duplicate 'AttributeUsage' attribute
xxx\UnitGenerator\UnitGenerator.SourceGenerator\UnitOfAttribute.cs(17,16,17,31): error CS0111: Type 'UnitOfAttribute' already defines a member called 'UnitOfAttribute' with the same parameter types

```

A possible fix would be to skip the generation if the class is already found:
```
var isAlreadyGenerated = context.Compilation.GetTypeByMetadataName($"UnitGenerator.UnitOfAttribute");
```

I'm not really sure why this class attribute (`UnitOfAttribute`) is generated and not directly included within the UnitGenerator lib.

Regards,
Adrien.

**Comment by neuecc** [comment]
`GeneratorPostInitializationContext` has no Compilation so can not check it.
All generated UnitOfAttribute is `internal` type so will not conflict I think.

**Comment by pellea** [comment]
The namespace used in the generated file is `namespace UnitGenerator`. So even if this is internal it would conflict as each class is generated in the same namespace and not in the namespace of the containing project.

```
﻿// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY UnitGenerator. DO NOT CHANGE IT.
// </auto-generated>
#pragma warning disable CS8669
#pragma warning disable CS8625
using System;

namespace UnitGenerator
{
    [AttributeUsage(AttributeTargets.Struct, AllowMultiple = false)]
    internal class UnitOfAttribute : Attribute
    {
```

**Comment by neuecc** [comment]
I don't really understand the situation.
Could you provide reproducible project?
